# Generated by Django 4.0 on 2022-05-18 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 10, 29, 16, 161694, tzinfo=utc)),
        ),
    ]
