# Generated by Django 4.0 on 2022-05-18 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_messages_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
