# Generated by Django 4.0 on 2022-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_messages_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='cont',
            field=models.CharField(default='nothing', max_length=1100000000000000),
        ),
    ]
