# Generated by Django 4.0.4 on 2022-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_messages_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computers',
            name='sid',
            field=models.CharField(default=None, max_length=110),
        ),
        migrations.AlterField(
            model_name='messages',
            name='to',
            field=models.CharField(default='me', max_length=110),
        ),
    ]
